### ISSUE TITLE
Moving backwards will eventually create a new workspace

### ISSUE THREAD

**Issue by hvitoi** [CheesyPhoenix/hyprland-relative-workspace#1]
## Problem

Moving backwards will eventually create a new workspace

## Steps to reproduce

- Be at a workspace whose ID is 2 (or any id higher than 1)
- Move/focus backwards `hyprland-relative-workspace b`
- This will create a new workspace with ID 1

## Expected behavior

The expected behavior is to stay that workspace 2 and create no new workspace

**Comment by CheesyPhoenix** [comment]
This is intended behavior, however i can add a flag to disable this

**Comment by CheesyPhoenix** [comment]
New flag added as of v1.1.0: ``--no-create-new``, this prevents **ALL** creation of new workspaces.

**Comment by hvitoi** [comment]
Hey, sorry for the confusion but that's not exactly the behavior I had in mind.
In my view it should not create new workspaces only when moving backwards. 
When moving forwards this is indeed the expected action (to create a new empty workspace)

**Comment by CheesyPhoenix** [comment]
> Hey, sorry for the confusion but that's not exactly the behavior I had in mind.
> In my view it should not create new workspaces only when moving backwards. 
> When moving forwards this is indeed the expected action (to create a new empty workspace)

Then i would recommend only using the flag with your backwards keybind.
